language: java

install: echo "I trust Maven."

# don't just run the tests, also run Findbugs and friends
#script: mvn verify cobertura:cobertura coveralls:cobertura
script: mvn clean install

jdk:
  - oraclejdk7

notifications:
  # See http://about.travis-ci.org/docs/user/build-configuration/ to learn more
  # about configuring notification recipients and more.
  email:
    recipients:
      - sean.scanlon@gmail.com
env:
  global:
    - secure: "ZzUSjCrRJXkf9MDdot71GWSK89OViETn+vy/jqBK7qv71W7gTJsgYUYeifU3\ntNHuSpBJ5fzDJmk2bIfyimXN0CRJu0HrcT25Dr1PNXPJbqh/z6HpHfSp2rW1\n9pf0jieHQPHPDwSAWEq6laIOHvFGI9VzL7wGSRi1NbECS1dQb3M="
